version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./DockerfileNG
    restart: always
    ports:
      - "8000"
    volumes:
      - ralph_static:/var/local/ralph
      - ralph_media:/usr/share/ralph/static
    links:
      - db:db
      - redis:redis
    env_file:
      - ./ralph.env

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - web:web
    volumes:
      - ./ralph.conf.nginx:/etc/nginx/conf.d/default.conf
      - ralph_media:/opt/static
      - ralph_static:/opt/media

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes:
      - ralph_dbdata:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:3.0
    restart: always
    ports:
      - "6379"

  inkpy:
    image: ar4s/inkpy_jinja:latest
    restart: always
    links:
      - redis:redis
    env_file:
      - ./ralph.env

volumes:
  ralph_dbdata:
  ralph_media:
  ralph_static:
