version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes:
      - dbdata:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  web:
    build:
      context: ./provision
      dockerfile: ./DockerfileNG
    restart: always
    ports:
      - "8000"
    links:
      - db:db
      - redis:redis
    env_file:
      - ./ralph.env

  redis:
    image: redis:3.0
    restart: always
    ports:
      - "6379"

  inkpy:
    image: ar4s/inkpy_jinja:latest
    restart: always
    links:
      - redis:redis
    env_file:
      - ./ralph.env

volumes:
  dbdata:
